config/routes.rb
Easyblog::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :posts do
    member do
      get :mark_archived
    end
  end
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Taggable
  include Mongoid::Timestamps

  field :body, type: String
  field :title, type: String
  field :archived, type: Boolean, default: false

  validates_presence_of :body, :title

  belongs_to :user

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  validates_presence_of :email
  validates_presence_of :encrypted_password

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  index({ email: 1 }, { unique: true, background: true })
  validates_presence_of :name
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :created_at, :updated_at

  field :name, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :display_flash_notice

  private

  def display_flash_notice
    flash[:notice] = "this is a test project for netguru"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  expose_decorated(:posts) { Post.where(archived: false) }
  expose_decorated(:post)

  def index
  end

  def new
  end

  def edit
  end

  def update
    if post.save
      render action: :index
    else
      render :new
    end
  end

  def destroy
    post = current_user.posts.find(params[:id]).destroy if post.present?

    render action: :index
  end

  def show
  end

  def mark_archived
    post = Post.find(params[:id])
    post.archived = true
    post.save

    render action: :index
  end

  def create
    if post.save
      redirect_to action: :index
    else
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Easyblog", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Posts', posts_path
    %li
      = link_to 'Edit account', edit_user_registration_path
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Easyblog"
      %meta{:content => content_for?(:description) ? yield(:description) : "Easyblog", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/posts/_form.haml
= simple_form_for post, html: { class: "form-horizontal" } do |f|
  = f.input :title
  = f.input :body, as: :text, input_html: { cols: 50, rows: 3 }
  = f.input :tags, as: :text, hint: "comma separated values", input_html: { cols: 50, rows: 3 }
  = f.button :submit

app/views/posts/edit.haml
.page-header
  %h1 edit post

= render "form"

app/views/posts/index.haml
%h1
  posts
  %small
    = "(#{posts.count})"
    = link_to "add new", new_post_path

- posts.each do |post|
  %li
    = link_to post.title, post_path(post)

app/views/posts/new.haml
.page-header
  %h1 new post

= render "form"

app/views/posts/show.haml
.page-header
  %h2
    = post.title
    %small
      = post.created_at
      = link_to "edit", edit_post_path(post)

.post
  = post.body
.tags
  = post.tags

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}